### ISSUE TITLE
Not able to fetch the items anymore

### ISSUE THREAD

**Issue by Azzeccagarbugli** [ahivert/tgtg-python#189]
Hello @ahivert, first of all, thanks for this super handy client. I just wanted to report a problem I encountered while developing a side project. 

Basically, when I'm trying to log in, or sometimes when I'm trying to fetch the complete list of items, I get a status code equal to `403` with the following reported HTML:

```html
tgtg.exceptions.TgtgLoginError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'cid\':\'AHrlqAAAAAMAU3Qjyk95ipMA2Wkvag==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35587,\'e\':\'38fdf8c8806028bc7b010dc826ec31e86f0ac1329c5f86a3deddada3ccde44cf\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')
```

Seems that my account is restricted to some sort of captcha that I don't know how to unlock anymore and it's blocking my requests toward the `API`. Just once when I tried to open the app to check if the official servers were up I noticed that they were asking me for the captcha confirmation in the app itself but besides that time nothing more...

I have seen that there were multiple opened issues about this specific error but they were almost all related to the `login` endpoint and never to the `items` one.

Thanks a lot in advance!

**Comment by Azzeccagarbugli** [comment]
The service started to work again on its own, I really don't know what happened. I'm closing this for now!

**Comment by ghecko** [comment]
Hi,

I encounter the same problem during the client authentication:

```
Using version 22.9.10
Traceback (most recent call last):
  File "tgtg-alerts.py", line 42, in <module>
    main()
  File "tgtg-alerts.py", line 8, in main
    token = client.get_credentials()
  File "/usr/local/lib/python3.10/dist-packages/tgtg/__init__.py", line 84, in get_credentials
    self.login()
  File "/usr/local/lib/python3.10/dist-packages/tgtg/__init__.py", line 165, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'cid\':\'AHrlqAAAAAMA93PIG3AH-zAAVEvhNA==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35587,\'e\':\'0d8230bb1520a6625b31cd5358fadcfecf8c6a16d692d82b7718b705a2dd3945\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')
```
