### ISSUE TITLE
cannot import name 'TgtgClient' from partially initialized module 'tgtg' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by matkoniecz** [ahivert/tgtg-python#260]
```
from tgtg import TgtgClient
```
from readme gives

```
Traceback (most recent call last):
  File "tgtg.py", line 1, in <module>
    from tgtg import TgtgClient
  File "/home/mateusz/Desktop/tmp/tgtg.py", line 1, in <module>
    from tgtg import TgtgClient
ImportError: cannot import name 'TgtgClient' from partially initialized module 'tgtg' (most likely due to a circular import) (/home/mateusz/Desktop/tmp/tgtg.py)
```

**Comment by matkoniecz** [comment]
```
import tgtg

client = tgtg.TgtgClient(email=<emall>)
```

also fails

**Comment by matkoniecz** [comment]
Python 3.8.10

**Comment by ahivert** [comment]
looks good on my side
![image](https://github.com/ahivert/tgtg-python/assets/11361874/b3f0bea9-7409-402c-a7f5-8c2cf516a47d)

**Comment by matkoniecz** [comment]
hmm, maybe I will test on fresh VM

**Comment by icorvus** [comment]
The filename that you are trying to run is `tgtg.py`, the same as the package name. Seems that this is the problem.  I also reproduced it on my machine and changing the filename resolved the issue.

**Comment by matkoniecz** [comment]
thanks, this fixed it!
