### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by teHwHoly** [ahivert/tgtg-python#321]
Hi,

your API worked amazing until now, thank you so much for it!
Two days ago it started throwing this error:
```
Traceback (most recent call last):
  File "/toogood.py", line 24, in <module>
    items = client.get_items()
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tgtg/__init__.py", line 244, in get_items
    self.login()
  File "/usr/local/lib/python3.11/dist-packages/tgtg/__init__.py", line 153, in login
    self._refresh_token()
  File "/usr/local/lib/python3.11/dist-packages/tgtg/__init__.py", line 139, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid= [..] "}')
```
Seems like they implemented some captcha method, didn't they?
I left out some information of the URL ([..]).
Does anybody else also get this error?
I'm from Germany, just in case the changes done were regional.

Thanks!

**Comment by Marow** [comment]
Same here. Got Captcha 403 error when trying to get_items

**Comment by Cruiser79** [comment]
I also got a 403 and the response with a captcha url. To solve the captcha didn't helped. So i stopped my tgtg application yesterday midday. I started it again this morning and everything was working.
So maybe the solution is only: wait many hours, if you got a captcha!?

**Comment by TanguyOrtegat** [comment]
same here ...

**Comment by vandrham** [comment]
I get the same when I run the login flow on a remote VPS and open the e-mail confirmation in a browser on my local browser (on a different IP address than the login call). When I perform both on the same source IP everything seems to work fine.

I suspect that the cookies that are the result of the login call are bound to the IP address of the caller and need to be confirmed using a browser session coming from the same IP address.

**Comment by simplearetenir** [comment]
The error is back.

**Comment by TanguyOrtegat** [comment]
Yes indeed, keep getring error 

> The error is back.

**Comment by ThatOtherAndrew** [comment]
Exact same issue here, unfortunately.

**Comment by gregsadetsky** [comment]
same! thanks a lot

**Comment by Barzou** [comment]
Same here. This issue should be reopen or a new one created I guess @ahivert 

For my case, I didn't make it work and have captcha error everytime. May be I tried too many times to setup my project.
I switched the language to the same I use on the app, it didn't change anything.

**Comment by reidmeyer** [comment]
@Barzou , can you clarify how you changed the language? I'm running a script in google cloud, and I do email verification from my phone. Was it the language that fixed the issue for you?
